name: Run All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew file
        run: chmod +x gradlew

      - name: Run All tests
        run: ./gradlew clean test

      - name: Publish test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/cucumber-report/cucumber-html-reports
